name: Unzip File

on:
  push:
    paths:
      - Model/Grid_cameras.zip

jobs:
  unzip:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository content
        uses: actions/checkout@v2

      - name: Unzip file
        run: unzip -o Model/Grid_cameras.zip -d Model
